apiVersion: v1
kind: Service
metadata:
  name: kafka-connect
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 8083
    targetPort: 8083
    name: rest-api
  selector:
    app: kafka-connect
