apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-producer-demo
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: kafka-producer
        image: confluentinc/cp-kafka:7.4.0
        command:
        - /bin/bash
        - -c
        - |
          echo "Starting Kafka producer demo..."
          
          # Wait for Kafka to be ready
          echo "Waiting for Kafka to be ready..."
          kafka-topics --bootstrap-server kafka:9092 --list
          
          # Create topic if it doesn't exist
          echo "Creating topic demo-messages..."
          kafka-topics --bootstrap-server kafka:9092 --create --topic demo-messages --partitions 3 --replication-factor 1 --if-not-exists
          
          # Produce sample messages
          echo "Producing sample messages..."
          for i in {1..10}; do
            timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
            message_id=$(uuidgen)
            content="Demo message number $i"
            
            echo "{\"message_id\":\"$message_id\",\"timestamp\":\"$timestamp\",\"content\":\"$content\",\"sequence\":$i}" | \
            kafka-console-producer --bootstrap-server kafka:9092 --topic demo-messages
            
            echo "Sent message $i"
            sleep 2
          done
          
          echo "Demo producer completed successfully!"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
      restartPolicy: Never
  backoffLimit: 3
